### ISSUE TITLE
2016/10/02 現在のオトクな情報や技術情報

### ISSUE THREAD

**Issue by ogasawaraShinnosuke** [DreamHackers/hackathon#13]
### Add  article
- オトクな情報
- 技術
### Limits

5/人

**Comment by Gaddict** [comment]
AdsenseとかAnalyticsを無効化するChrome拡張機能
Ghostery
https://www.ptengine.jp/blog/index.php/ghostery/

**Comment by ogasawaraShinnosuke** [comment]
買い物の“お釣り”で投資できるFinTechアプリ
https://www.moneyboxapp.com/

**Comment by kouares** [comment]
REST APIをテストするのに便利なChrome拡張機能
DHC REST Client
http://blog.mah-lab.com/2014/08/26/chrome-rest-api-testing/

**Comment by Gaddict** [comment]
Googleの無料Font（かなり色々ある）
https://fonts.google.com/

**Comment by Gaddict** [comment]
Webページ閲覧時にCSSを自動で上書き適用するChrome拡張
http://hapilaki.hateblo.jp/entry/google-chrome-stylebot

**Comment by Gaddict** [comment]
年利5%以上で資産運用できる ソーシャルレンディング
株主にGMO, SMBCがいる
https://www.maneo.jp/

**Comment by kouares** [comment]
googleのBaas - Firebase
https://html5experts.jp/technohippy/18040/

**Comment by ogasawaraShinnosuke** [comment]
LINE API
https://developers.line.me/

**Comment by Gaddict** [comment]
気になるサイトのアクセス数とかを調べられる
https://www.similarweb.com/

**Comment by ogasawaraShinnosuke** [comment]
プログラミングのサイドプロジェクトを始めたいきさつ
http://postd.cc/how-i-got-started-with-programming-side-projects/

**Comment by ogasawaraShinnosuke** [comment]
完全ワイヤレスイヤホン
http://www.e-earphone.jp/blog/?p=56078

**Comment by kouares** [comment]
Django pythonのwebアプリケーションフレームワーク
http://djangoproject.jp/

**Comment by kouares** [comment]
Kubernetes Dockerとセットで使う
https://www.wantedly.com/companies/wantedly/post_articles/30236

**Comment by ogasawaraShinnosuke** [comment]
Google Maps Web Services APIs のクライアントライブラリを使ってみよう
https://googledevjp.blogspot.jp/2016/09/google-maps-web-services-apis.html

**Comment by kouares** [comment]
GCP このスケールするスピードはヤバイと思う
https://cloudplatform.googleblog.com/2016/09/bringing-Pokemon-GO-to-life-on-Google-Cloud.html
